application: ubuntu-faq
version: 33
runtime: python
api_version: 1

default_expiration: "3d"

handlers:
- url: /img
  static_dir: img

- url: /favicon.ico
  static_files: img/favicon.ico
  upload: img/favicon.ico

- url: /tasks/emails
  script: emails.py
  login: admin

- url: /tasks/enlaces
  script: enlaces.py
  login: admin

- url: /tasks/karma
  script: karma.py
  login: admin

- url: /sitemap
  script: sitemap.py

- url: /sitemap.xml
  script: sitemap.py

- url: /rss
  script: rss.py

- url: /rss-respuestas
  script: rssr.py

- url: /robots.txt
  script: robots.py

- url: /pingbacks
  script: pingbacks.py

- url: .*
  script: main.py
