application: ubuntu-faq
version: 51
runtime: python
api_version: 1
default_expiration: "3d"

handlers:
- url: /img
  static_dir: img

- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: img/favicon.ico
  upload: img/favicon.ico

- url: /cron/antiguas
  script: cron/antiguas.py
  login: admin

- url: /cron/emails
  script: cron/emails.py
  login: admin

- url: /cron/memcache
  script: cron/memcache.py
  login: admin

- url: /cron/karma
  script: cron/karma.py
  login: admin

- url: /cron/rss-scanner
  script: cron/rss-scanner.py
  login: admin

- url: /cron/seguimientos
  script: cron/seguimientos.py
  login: admin

- url: /cron/stats
  script: cron/stats.py
  login: admin

- url: /cron/steam
  script: cron/steam.py
  login: admin

- url: /cron/tags
  script: cron/tags.py
  login: admin

- url: /robots.txt
  script: robots.py

- url: /stop_emails
  script: stop_emails.py
  login: required

- url: /u/.*
  script: usuarios.py
  login: required

- url: /noti/.*
  script: notificaciones.py
  login: required

- url: /seguir/.*
  script: seguimiento.py
  login: required

- url: .*
  script: public.py
