application: ubuntu-faq
version: 46
runtime: python
api_version: 1

default_expiration: "2d"

handlers:
- url: /img
  static_dir: img

- url: /favicon.ico
  static_files: img/favicon.ico
  upload: img/favicon.ico

- url: /tasks/antiguas
  script: tasks/antiguas.py
  login: admin

- url: /tasks/emails
  script: tasks/emails.py
  login: admin

- url: /tasks/enlaces
  script: tasks/enlaces.py
  login: admin

- url: /tasks/memcache
  script: tasks/memcache.py
  login: admin

- url: /tasks/karma
  script: tasks/karma.py
  login: admin

- url: /tasks/rss-scanner
  script: tasks/rss-scanner.py
  login: admin

- url: /tasks/seguimientos
  script: tasks/seguimientos.py
  login: admin

- url: /tasks/stats
  script: tasks/stats.py
  login: admin

- url: /tasks/steam
  script: tasks/steam.py
  login: admin

- url: /tasks/tags
  script: tasks/tags.py
  login: admin

- url: /sitemap
  script: sitemap.py

- url: /sitemap.xml
  script: sitemap.py

- url: /rss
  script: rss.py

- url: /rss-respuestas
  script: rssr.py

- url: /robots.txt
  script: robots.py

- url: /steam4linux
  script: steam4linux.py

- url: /stop_emails
  script: stop_emails.py
  login: required

- url: /tag/.*
  script: tags.py

- url: /votar/.*
  script: votar.py

- url: /u/.*
  script: usuarios.py
  login: required

- url: /noti/.*
  script: notificaciones.py
  login: required

- url: /seguir/.*
  script: seguimiento.py
  login: required

- url: .*
  script: main.py
