application: ubuntu-faq
version: 28
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /favicon.ico
  static_files: img/favicon.ico
  upload: img/favicon.ico

- url: /tasks/emails
  script: emails.py
  login: admin

- url: /tasks/enlaces
  script: enlaces.py
  login: admin

- url: /tasks/karma
  script: karma.py
  login: admin

- url: .*
  script: main.py
